import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

const aggro = localFont({
  src: [
    {
      path: "./fonts/SB-Aggro-L.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/SB-Aggro-M.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/SB-Aggro-B.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-aggro",
});

export const metadata: Metadata = {
  title: "MINHYUKFOLIO | 신민혁 포트폴리오",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${pretendard.variable} ${aggro.variable}  antialiased`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
