import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'MINHYUKFOLIO | 신민혁 포트폴리오',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
